//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compress.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompressUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R0VNOC1VLEZBMDYzNDIuMTUNCkhCOTdaU0pUQ0xSWU5QS0lRVlhEOiBPVw==.
        /// </summary>
        internal static string DefaultDictionaryKeys {
            get {
                return ResourceManager.GetString("DefaultDictionaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NjQ1MjcsMTUxMzQwLDEwNzI4OCwxNDU2MDgwLDM0Mjg5LDEyMTM3LDM1MDAwMDAsNTEzNDY1LDI1MTMxOSwxNDM1NzE3LDEyODk1NjgsOTMzMzIzLDk2NjYyMywxMDAxOTkxLDQ1MzQ5NSwxNDYxNzgxLDEwMTgwNjIsNTAwMDAwLDUwMDAwMCwzNzg5NjAsMjg4MzY5LDExMjg5NjUsMTA3NjIxNiwzODU4Miw3MDE1OCw5MTg2NywzOTg0Nyw1NjAyNCwyNzk1OSw2NDY3OSwzMjU4OSwzNzg1NiwyNzQ0OCwxNzM5Niw2OTc0LDMyMzM4LDM0MCwyNjcsMjMzMjMsMzEzNiw1MDY0LDE0MDA5LDE1Mw==.
        /// </summary>
        internal static string DefaultDictionaryValues {
            get {
                return ResourceManager.GetString("DefaultDictionaryValues", resourceCulture);
            }
        }
    }
}
